[entryPoints]
    [entryPoints.http]
    address = ":8080"
    [entryPoints.traefik]
    address = ":8081"

[api]
    dashboard = true
    insecure  = true

# Enable Consul Catalog configuration backend.
[providers.consulCatalog]
    prefix           = "traefik"
    exposedByDefault = false

    [providers.consulCatalog.endpoint]
      address = "192.168.56.20:8501"
      scheme  = "https"

        [providers.consulCatalog.endpoint.tls]
            ca = "/etc/traefik/consul-agent-ca.pem"
