cluster_domain      = "uprisiesoft.ch"
token               = "8QdhKCHc8Gq43nUBIBqQKq9Zp1C4uBR3KUggnpDhY4nugTfCl7efTnwcE8VUWXCO"
region              = "nbg1"
connection_key_file = "~/.ssh/id_rma"
admin_key_name		= "rma"
#letsencrypt_server	= "https://acme-staging-v02.api.letsencrypt.org/directory"
#letsencrypt_server	= "https://acme-v01.api.letsencrypt.org/directory"