variable "nodename" {}
variable "node_active" {}
variable "cluster_domain" {}
variable "token" {}
variable "region" {}
variable "instance_type" {}
variable "connection_key_file" {}
variable "admin_key_name" {}
variable "private_net_id" {}
variable "primary_public_ip" {}
variable "primary_private_ip" {}
variable "node_connect_hash" {}